### ISSUE TITLE
百度搞的这个东西很不错额

### ISSUE THREAD

**Issue by osdio** [FED-Div/divReading#2]
话说FED-DIV指什么意思？

**Comment by izayl** [comment]
Front End Div  队名叫Div 

谢家兴
izayl@163.com

**Comment by izayl** [comment]
@soliury 
可以帮我内推美团实习吗？现在大三 🤗

**Comment by osdio** [comment]
接下来正好我们部门有点确认，可以来试试

**Comment by izayl** [comment]
可以留个联系方式吗？ 

谢家兴
izayl@163.com

**Comment by osdio** [comment]
我github上应该能找到联系方式吧
